# Generated by Django 5.0 on 2024-01-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
